#+TILE: Literate HDF5

#+PROPERTY: header-args :eval never-export

* Table of Contents

- [[file:./checklist.org][Checklist]]
- [[file:./hdf5-intro.org][HDF5 Introduction]]
- [[file:./c-lambda.org][Let It Be Lambda (λ)]]
- [[file:./fsm.org][Tracking HDF5 Free Space]]
- [[file:./core-vfd.org][Using Memory-Backed HDF5 Files to Reduce Storage Access and Size]]

* Caveat Emptor

Each example in this collection tells a story and, to a degree, is fiction. The
reality and demands of professional software developments are much harsher, and
are /not/ met by the code examples provided. For example, no error detection or
handling was attempted, and attentive readers will easily identify several
corner cases that were not considered. The code examples in this collection are
for illustration only.

* Cohortatio ad Gentiles

Enjoy perusing the Org (text!) files rendered reasonably well courtesy of
[[https://github.com/][GitHub]].  Believe it or not, all artifacts (code examples, images, etc.) are
generated from the Org files, but they are repeated /for your convenience/ in
the appropriate sub-directories.

If you develop a sense that you are missing a lot, consider [[https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ][learning Emacs]] and
becoming an [[https://www.masteringemacs.org/][Emacs master]].

* To Emacs Users

Derek Feichtinger's [[https://github.com/dfeich/org-babel-examples][repo of Org Babel examples]] is a constant source of
inspiration. Check it out!

For your own sanity and that of those around you, I recommend you first run
through the [[file:./checklist.org][checklist]].

There are several ways to run the C examples contained in these documents.  You
can execute the code blocks containing =main= functions directly via =C-c C-c= ,
provided the HDF5 library is in your =LD_LIBRARY_PATH= and [[https://gcc.gnu.org/][GCC]] knows where to
find the HDF5 header files and library. If the =h5cc= compiler wrapper is in
your =PATH=, execute the following block:

#+begin_src emacs-lisp :results silent

(setq org-babel-C-compiler "h5cc --std=gnu99 ")

#+end_src

For parallel HDF5 examples use:

#+begin_src emacs-lisp :results silent

(setq org-babel-C-compiler "HDF5_CC=mpicc h5cc --std=gnu99 ")

#+end_src

and don't forget to link against the MPI library!

(*Caveat:* I have not yet figured out a way to invoke the executable with =mpirun/mpiexec/srun=.)

Otherwise, you have to be more specfic. For example:

#+begin_src emacs-lisp :results silent

(setq org-babel-C-compiler
      (concat "gcc --std=gnu99 "
              "-I/home/gerdheber/.local/include "
              "-L/home/gerdheber/.local/lib "))

#+end_src

You will also need to specify the libraries against which to link with a =:libs= source code block header. (See [[https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-C.html][C, C++, D Source Code Blocks in Org Mode]].)

Create the examples' source code by "tangling" via =C-c C-v t= from Emacs or
from the command line by running

   #+begin_example

   emacs --batch --eval "(require 'org)" \
         --eval '(org-babel-tangle-file "<filename>.org")'

   #+end_example

The code can then be compiled with =gcc --std=gnu99 ...= and the appropriate
include and library paths for HDF5, MPI, etc.
